name: e2e test
on:
  pull_request:
    types: [ synchronize ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Run
        run: npm run start

      - name: Run cypress
        uses: cypress-io/github-action@v5
        with:
          browser: chrome
